### ISSUE TITLE
TypeError unter ruby 1.9.2

### ISSUE THREAD

**Issue by toyflish** [giniedp/fancygrid#1]
bei Verwendung unter ruby 1.9.2 mit rails 3.0.6 kommt folgender Fehler beim aufruf von grid.find

grid.find( :order => "spots.created_at DESC" )

TypeError (can't convert Symbol into Integer):
  app/controllers/admin/spots_controller.rb:17:in `block in index'
  app/controllers/admin/spots_controller.rb:6:in`index'

.. aufgetreten in msurfg

Gruß Kai

**Comment by giniedp** [comment]
Magst mir da mal einen kompletten Trace ausgeben?
