### ISSUE TITLE
Don't require searching with 1 or 0 when true/false or yes/no

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#10]
We are currently using this to display some fields that can be true or false. However, our customers prefer yes/no over true false.

Do you have a general approach how best this can be achieved ? 

Ideally, yes/no would be used, however, true/false would be much better than 0 and 1 for searching.

Should the conditions be modified via JS or should the backend handle it? Any thoughts on how we can help avoid the issue of searching for "yes" on a non-boolean field that contains "yes"?

**Comment by giniedp** [comment]
yes, there is already a functionality for this. After you setup your column, you can add search filters like this

```
fancygrid_for :posts do |g|
    # ...
    g.columns :enabled
    # ...
    g.search_filter "posts.enabled", [["-- choose filter --", nil], ["NO", 0], ["YES", 1]]
    # ...
end
```

This will automaticly create a select box instead a text field for a column. At least for the simple search. I'm not sure what will happen with the complex search
