### ISSUE TITLE
Failure when NULL in Database

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#11]
FancyGrid currently selects all like so:

```
SELECT COUNT(*) FROM `agencies` WHERE (( agencies.id LIKE ('%%') ) 
AND (      agencies.name LIKE ('%%') ) AND ( agencies.status LIKE ('%prospective%') )
AND ( agencies.mailing_address_state LIKE ('%%') ) AND ( agencies.direct_bill LIKE 
 ('%%') ))

+----------+
| COUNT(*) |
+----------+
|        0 | 
+----------+
1 row in set (0.00 sec)
```

The problem is that for records that have a nil value in mailing_address_state or direct_bill the statement returns no records, when it should. If these were blank strings, this query would be correct.

```
SELECT COUNT(*) FROM `agencies` WHERE (( agencies.id LIKE ('%%') ) AND (   
agencies.name LIKE ('%%') ) AND ( agencies.status LIKE ('%prospective%') ));

+----------+
| COUNT(*) |
+----------+
|        3 |
+----------+
1 row in set (0.00 sec)
```

This returns the correct amount because it ignores the nil columns. 

Is this something that might be fixed or is there a current work around?

**Comment by giniedp** [comment]
Thanks for the report. I applied a fix, so now all empty LIKE conditions are just igonred by fancygrid.

**Comment by noahc** [comment]
Is there a way to specify exact matches? We have the term "active" and "inactive" and when we do a search using a search filter drop down we get both results back. Can we use the search filter drop down as an exact match search in someway?

Also, tested out your changes and they work as advertised.

**Comment by giniedp** [comment]
Good point. I changed the operator from "like" to "starts_with" only for the case, when the search has a dropdown filter. This should fix your isseue, but still leaves the issue open for the case that is other way round, like "foo" and "foobar".

I need to review the implementation and think about possible solutions, so please leave this issue open.

**Comment by noahc** [comment]
I thought about this last night a bit.

Currently, I have something like this:

`g.attributes :id, :name, :status, :mailing_address_state, :direct_bill`

could you change this to something like: 

`g.attributes id: :exact, name: :like, status: :exact, mailing_address_state: :starts_with, direct_bill: :exact`

And maybe default to like?
