### ISSUE TITLE
undefined method `search_options=' for nil:NilClass

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#12]
I have something like the following

```
fancygrid_for :contract_bonds, hide_search: false do |g|
g.tr_class = "results"
g.attributes :id, :bond_number,  :closed, :contract_amount


  g.table_class = "alternating"

  g.ajax_url = contract_bonds_path

  g.search_filter "contract_bonds.bond_number", [["-- choose filter --", nil]]

  g.find
```

And I get the error: "undefined method `search_options=' for nil:NilClass". I've looked at https://github.com/giniedp/fancygrid/issues/10 which shows how to do this, and I have the search.filter working in other parts of the application. I inspected the code, and didn't see anything obvious on what might be the problem. Do you have any thoughts on what might be causing this?

**Comment by giniedp** [comment]
have you got it working?
Usually the search_filter is applied to the column object that has the identifier "<table_name>.<name>". The name seems to be right in this example, which is "bond_number". So i assume your resource contract_bonds has a different table name than "contract_bonds". If this is not the case, then you should debug the state of your setup. Iterate over all nodes and columns and inspect the "identifier" method of each.

**Comment by noahc** [comment]
That is correct. I changed contract_bonds to bonds, which fixed this.
