### ISSUE TITLE
how do you hide a column?

### ISSUE THREAD

**Issue by kris-luminar** [giniedp/fancygrid#14]
I see a setter in the source code for visible and things like `fancygrid.visible_columns` but can't figure out how to actually set a column to be hidden.

**Comment by giniedp** [comment]
When you define the columns, you can pass an options hash with the option :visible => false

```
g.columns :name, :visible => false
```

This will tell the fancygrid not to render that column(s). This is meant for the feature that allows to sort and enable/disable the columns in the frontend. To enable that feature, you have to add the :sort_window component to your fancygrid instance. Here is an example

```
fancygrid_for :projects do |g|
    g.components += [:sort_window]   # enables the sort window
    g.columns :name, :visible => false # this will be invisible per default
    # ... other options and setup
end
```

**Comment by kris-luminar** [comment]
@giniedp thanks for getting back to me on this!
