### ISSUE TITLE
FancyGrid and Cucumber

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#5]
Has anyone had any issues using FancyGrid with Cucumber?

I'm using "agency" as my model. I create three agencies, yet Fancygrid can't seem to find them. 

When I have cucumber show me the page I get "Page 1 of 0". Which suggests its not grabbing the actual data.

But, I ask cucumber for a count and I get 3. This works in a browser, and so it has to be something with the way cucumber and capybara are interacting with fancygrid. I even went so far as to recreate the data via Factorygirl that cucumber is creating and that works fine.

Any thoughts on this or has anyone experienced this?

**Comment by giniedp** [comment]
Fancygrid fetches the data via ajax, so you have to setup your testenvironment to process javascript and to wait for ajax requests to finish.

**Comment by noahc** [comment]
Wow, that was super fast.

I just figured it out though. I was creating my Agencies after visiting the page. 

Thanks for the suggestion though.
