### ISSUE TITLE
Add Classes/ID's to view output

### ISSUE THREAD

**Issue by noahc** [giniedp/fancygrid#6]
I already have the css I need in place to display table output like this. However, I need to add some id's and classes to outputs. Is there an example somewhere on how to do this?

**Comment by giniedp** [comment]
unfortunately there is currently no simple way to do this. For now, you could override the view at

```
views/fancygrid/table.html.haml
```

and add your output there, but that would be very hacky. I could try to add more options that you can pass into the builder. So you will be able to pass a symbol, string or a lambda to resolve the class or id. 
Can you give an example on what html tags you want to have the custom classes and ids?

**Comment by giniedp** [comment]
you can now add custom css classes and ids to TR and TD table elements. Here is an example

```
fancygrid_for :user do |g|
  #...
  g.tr_id do |record|
    "row-#{record.id}"
  end
  # or
  g.tr_id = :row_id
  # same with tr_class, td_id and td_class
end
```

gem is just released with version 2.0.2

**Comment by noahc** [comment]
Thanks! 

Can we also set a table class or id too?

With that I should be able to easily reuse our existing css.

**Comment by giniedp** [comment]
ok, i just added table_class and table_id getters and setters

**Comment by noahc** [comment]
Thanks. 

Do you have any thoughts on conditional classes for table rows generally? 

Or adding support for cycle? http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-cycle

I noticed in the css you have the nth-child, which works in modern browsers, however most of our customers don't use a modern browser that supports the nth-child(odd) feature. 

I've tried doing something like:

```
def index
  count = 0 
  fancygrid_for :agencies do |g|  
    if count.even? 
      g.tr_class = "results even"
    else
      g.tr_class = "results odd"
    end
    count += 1
    ...
    g.find
  end
end
```

Every table row got the class even.

**Comment by giniedp** [comment]
have you tried an instance variable @count? otherwise you can do it in the template, if you override it. i'll probably add the odd even classes this evening, since they are commonly used in tables

**Comment by giniedp** [comment]
odd even classes are now always added to tables

**Comment by noahc** [comment]
This is awesome. Thanks for all the help.
